BEGIN TRANSACTION;
INSERT INTO `estados` VALUES (1,'Acre',1,'AC');
INSERT INTO `estados` VALUES (2,'Alagoas',1,'AL');
INSERT INTO `estados` VALUES (3,'Amazonas',1,'AM');
INSERT INTO `estados` VALUES (4,'Amapá',1,'AP');
INSERT INTO `estados` VALUES (5,'Bahia',1,'BA');
INSERT INTO `estados` VALUES (6,'Ceará',1,'CE');
INSERT INTO `estados` VALUES (7,'Distrito Federal',1,'DF');
INSERT INTO `estados` VALUES (8,'Espírito Santo',1,'ES');
INSERT INTO `estados` VALUES (9,'Goiás',1,'GO');
INSERT INTO `estados` VALUES (10,'Maranhão',1,'MA');
INSERT INTO `estados` VALUES (11,'Minas Gerais',1,'MG');
INSERT INTO `estados` VALUES (12,'Mato Grosso do Sul',1,'MS');
INSERT INTO `estados` VALUES (13,'Mato Grosso',1,'MT');
INSERT INTO `estados` VALUES (14,'Pará',1,'PA');
INSERT INTO `estados` VALUES (15,'Paraíba',1,'PB');
INSERT INTO `estados` VALUES (16,'Pernambuco',1,'PE');
INSERT INTO `estados` VALUES (17,'Piauí',1,'PI');
INSERT INTO `estados` VALUES (18,'Paraná',1,'PR');
INSERT INTO `estados` VALUES (19,'Rio de Janeiro',1,'RJ');
INSERT INTO `estados` VALUES (20,'Rio Grande do Norte',1,'RN');
INSERT INTO `estados` VALUES (21,'Rondônia',1,'RO');
INSERT INTO `estados` VALUES (22,'Roraima',1,'RR');
INSERT INTO `estados` VALUES (23,'Rio Grande do Sul',1,'RS');
INSERT INTO `estados` VALUES (24,'Santa Catarina',1,'SC');
INSERT INTO `estados` VALUES (25,'Sergipe',1,'SE');
INSERT INTO `estados` VALUES (26,'São Paulo',1,'SP');
INSERT INTO `estados` VALUES (27,'Tocantins',1,'TO');
