BEGIN TRANSACTION;
CREATE TABLE "Professores" (
	`FK_CPF`	TEXT NOT NULL UNIQUE,
	`Titulacao`	TEXT NOT NULL,
	`Graduacao`	TEXT NOT NULL,
	PRIMARY KEY(`FK_CPF`),
	FOREIGN KEY(`FK_CPF`) REFERENCES Pessoas
);
CREATE TABLE "Pessoas" (
	`CPF`	TEXT NOT NULL UNIQUE,
	`Nome`	TEXT NOT NULL,
	`Data_Nascimento`	TEXT,
	`Endereco`	TEXT NOT NULL,
	`Setor`	TEXT NOT NULL,
	`FK_IDCidade`	INTEGER NOT NULL,
	`Telefone`	TEXT NOT NULL,
	`Email`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`CPF`)
);
CREATE TABLE "Matriculas" (
	`IDMatricula`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FK_IDAluno`	INTEGER NOT NULL,
	`FK_IDDisciplina`	INTEGER NOT NULL,
	`Ano`	INTEGER NOT NULL,
	`Semestre`	INTEGER NOT NULL,
	`Nota1`	INTEGER,
	`Nota2`	INTEGER,
	`NotaFinal`	INTEGER,
	FOREIGN KEY(`FK_IDAluno`) REFERENCES `Alunos`,
	FOREIGN KEY(`FK_IDDisciplina`) REFERENCES `Disciplinas`
);
CREATE TABLE "Estados" (
	`IDEstado`	INTEGER NOT NULL UNIQUE,
	`Estado`	TEXT NOT NULL,
	`Sigla`	TEXT NOT NULL,
	PRIMARY KEY(`IDEstado`)
);
CREATE TABLE "Disciplinas" (
	`IDDisciplina`	INTEGER NOT NULL UNIQUE,
	`Disciplina`	TEXT NOT NULL,
	`CargaHoraria`	REAL NOT NULL,
	`FK_CPFProfessor`	TEXT NOT NULL,
	`FK_IDCurso`	INTEGER,
	PRIMARY KEY(`IDDisciplina`),
	FOREIGN KEY(`FK_CPFProfessor`) REFERENCES `Professores`,
	FOREIGN KEY(`FK_IDCurso`) REFERENCES `Cursos`
);
CREATE TABLE "Cursos" (
	`IDCurso`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Curso`	TEXT NOT NULL,
	`Duracao`	REAL NOT NULL
);
CREATE TABLE "Cidades" (
	`IDCidade`	INTEGER NOT NULL UNIQUE,
	`Cidade`	TEXT NOT NULL,
	`FK_IDEstado`	INTEGER NOT NULL,
	PRIMARY KEY(`IDCidade`)
);
CREATE TABLE "Alunos" (
	`FK_CPF`	TEXT NOT NULL UNIQUE,
	`Matricula`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Ano`	INTEGER NOT NULL,
	`FK_IDCurso`	INTEGER NOT NULL,
	FOREIGN KEY(`FK_CPF`) REFERENCES `Pessoas`,
	FOREIGN KEY(`FK_IDCurso`) REFERENCES `Cursos`
);
COMMIT;
